export const IMAGE_BASE = "https://dz3we2x72f7ol.cloudfront.net/expansions/perfect-order/en-us";
export const IMAGE_CODE = "P614_EN";

export const HAS_REVERSE = new Set(["C", "U", "R"]);

export const RARITY_ORDER = ["C", "U", "R", "RR", "AR", "UR", "SIR", "Gold"];

export const RARITY_CONFIG = {
  C:    { label: "Common",                      color: "#94a3b8" },
  U:    { label: "Uncommon",                    color: "#34d399" },
  R:    { label: "Rare",                        color: "#60a5fa" },
  RR:   { label: "Double Rare",                 color: "#c084fc" },
  AR:   { label: "Art Rare",                    color: "#fb923c" },
  UR:   { label: "Special Rare",                color: "#f87171" },
  SIR:  { label: "Special Illustration Rare",   color: null },
  Gold: { label: "Gold",                        color: "#fbbf24" },
};

export const cards = [
  { number: 1,   name: "Spinarak",              rarity: "C",    regular: 27, reverse: 7,  price: 0.07,   priceReverse: 0.22,  value: 3.43   },
  { number: 2,   name: "Aridos",                rarity: "C",    regular: 18, reverse: 5,  price: 0.09,   priceReverse: 0.21,  value: 2.67   },
  { number: 3,   name: "Shaymin",               rarity: "U",    regular: 27, reverse: 5,  price: 0.06,   priceReverse: 0.22,  value: 2.72   },
  { number: 4,   name: "Snivy",                 rarity: "C",    regular: 21, reverse: 4,  price: 0.11,   priceReverse: 0.22,  value: 3.19   },
  { number: 5,   name: "Servine",               rarity: "C",    regular: 22, reverse: 6,  price: 0.09,   priceReverse: 0.20,  value: 3.18   },
  { number: 6,   name: "Serperior",             rarity: "R",    regular: 12, reverse: 3,  price: 0.12,   priceReverse: 0.23,  value: 2.13   },
  { number: 7,   name: "Scatterbug",            rarity: "C",    regular: 20, reverse: 10, price: 0.08,   priceReverse: 0.15,  value: 3.10   },
  { number: 8,   name: "Spewpa",                rarity: "C",    regular: 20, reverse: 4,  price: 0.08,   priceReverse: 0.19,  value: 2.36   },
  { number: 9,   name: "Vivillion",             rarity: "U",    regular: 24, reverse: 3,  price: 0.05,   priceReverse: 0.23,  value: 1.89   },
  { number: 10,  name: "Rowlet",                rarity: "C",    regular: 24, reverse: 3,  price: 0.08,   priceReverse: 0.25,  value: 2.67   },
  { number: 11,  name: "Dartrix",               rarity: "C",    regular: 21, reverse: 4,  price: 0.12,   priceReverse: 0.24,  value: 3.48   },
  { number: 12,  name: "Decidueye ex",          rarity: "RR",   regular: 4,  reverse: 0,  price: 0.50,                        value: 2.00   },
  { number: 13,  name: "Fletchinder",           rarity: "C",    regular: 19, reverse: 5,  price: 0.08,   priceReverse: 0.24,  value: 2.72   },
  { number: 14,  name: "Talonflame",            rarity: "U",    regular: 28, reverse: 5,  price: 0.09,   priceReverse: 0.27,  value: 3.87   },
  { number: 15,  name: "Salandit",              rarity: "C",    regular: 17, reverse: 9,  price: 0.11,   priceReverse: 0.26,  value: 4.21   },
  { number: 16,  name: "Salazzle ex",           rarity: "RR",   regular: 7,  reverse: 0,  price: 0.38,                        value: 2.66   },
  { number: 17,  name: "Turtonator",            rarity: "U",    regular: 25, reverse: 2,  price: 0.04,   priceReverse: 0.17,  value: 1.34   },
  { number: 18,  name: "Seel",                  rarity: "C",    regular: 20, reverse: 8,  price: 0.10,   priceReverse: 0.21,  value: 3.68   },
  { number: 19,  name: "Dewgong",               rarity: "R",    regular: 17, reverse: 5,  price: 0.14,   priceReverse: 0.27,  value: 3.73   },
  { number: 20,  name: "Staryu",                rarity: "C",    regular: 21, reverse: 4,  price: 0.18,   priceReverse: 0.21,  value: 4.62   },
  { number: 21,  name: "Mega Starmie ex",       rarity: "RR",   regular: 8,  reverse: 0,  price: 0.85,                        value: 6.80   },
  { number: 22,  name: "Lapras ex",             rarity: "RR",   regular: 5,  reverse: 0,  price: 0.49,                        value: 2.45   },
  { number: 23,  name: "Amaura",                rarity: "C",    regular: 24, reverse: 7,  price: 0.15,   priceReverse: 0.23,  value: 5.21   },
  { number: 24,  name: "Aurorus",               rarity: "R",    regular: 9,  reverse: 4,  price: 0.23,   priceReverse: 0.25,  value: 3.07   },
  { number: 25,  name: "Volcanion",             rarity: "U",    regular: 26, reverse: 3,  price: 0.06,   priceReverse: 0.22,  value: 2.22   },
  { number: 26,  name: "Shinx",                 rarity: "C",    regular: 20, reverse: 4,  price: 0.09,   priceReverse: 0.24,  value: 2.76   },
  { number: 27,  name: "Luxio",                 rarity: "U",    regular: 30, reverse: 6,  price: 0.09,   priceReverse: 0.23,  value: 4.08   },
  { number: 28,  name: "Luxray",                rarity: "R",    regular: 13, reverse: 3,  price: 0.14,   priceReverse: 0.30,  value: 2.72   },
  { number: 29,  name: "Dedenne",               rarity: "C",    regular: 18, reverse: 5,  price: 0.05,   priceReverse: 0.25,  value: 2.15   },
  { number: 30,  name: "Clefairy",              rarity: "C",    regular: 20, reverse: 5,  price: 0.09,   priceReverse: 0.25,  value: 3.05   },
  { number: 31,  name: "Mega Clefable ex",      rarity: "RR",   regular: 4,  reverse: 0,  price: 0.61,                        value: 2.44   },
  { number: 32,  name: "Mawile",                rarity: "C",    regular: 10, reverse: 6,  price: 0.09,   priceReverse: 0.18,  value: 1.98   },
  { number: 33,  name: "Espurr",                rarity: "C",    regular: 17, reverse: 7,  price: 0.07,   priceReverse: 0.26,  value: 3.01   },
  { number: 34,  name: "Meowstic",              rarity: "U",    regular: 28, reverse: 7,  price: 0.09,   priceReverse: 0.20,  value: 3.92   },
  { number: 35,  name: "Spritzee",              rarity: "C",    regular: 15, reverse: 2,  price: 0.16,   priceReverse: 0.33,  value: 3.06   },
  { number: 36,  name: "Aromatisse",            rarity: "U",    regular: 24, reverse: 4,  price: 0.08,   priceReverse: 0.22,  value: 2.80   },
  { number: 37,  name: "Nosepass",              rarity: "C",    regular: 21, reverse: 6,  price: 0.07,   priceReverse: 0.23,  value: 2.85   },
  { number: 38,  name: "Probopass",             rarity: "C",    regular: 20, reverse: 7,  price: 0.06,   priceReverse: 0.24,  value: 2.88   },
  { number: 39,  name: "Hippopoatas",           rarity: "C",    regular: 24, reverse: 5,  price: 0.07,   priceReverse: 0.25,  value: 2.93   },
  { number: 40,  name: "Hippowdon",             rarity: "U",    regular: 24, reverse: 5,  price: 0.03,   priceReverse: 0.21,  value: 1.77   },
  { number: 41,  name: "Landorus",              rarity: "R",    regular: 14, reverse: 2,  price: 0.07,   priceReverse: 0.22,  value: 1.42   },
  { number: 42,  name: "Binacle",               rarity: "C",    regular: 21, reverse: 5,  price: 0.20,   priceReverse: 0.23,  value: 5.35   },
  { number: 43,  name: "Barbarcle",             rarity: "U",    regular: 23, reverse: 4,  price: 0.15,   priceReverse: 0.27,  value: 4.53   },
  { number: 44,  name: "Tyrunt",                rarity: "C",    regular: 21, reverse: 4,  price: 0.18,   priceReverse: 0.22,  value: 4.66   },
  { number: 45,  name: "Tyrantrum",             rarity: "R",    regular: 19, reverse: 7,  price: 0.30,   priceReverse: 0.28,  value: 7.66   },
  { number: 46,  name: "Hawlucha",              rarity: "C",    regular: 22, reverse: 4,  price: 0.04,   priceReverse: 0.24,  value: 1.84   },
  { number: 47,  name: "Mega Zygarde ex",       rarity: "RR",   regular: 3,  reverse: 0,  price: 0.49,                        value: 1.47   },
  { number: 48,  name: "Gastly",                rarity: "C",    regular: 20, reverse: 5,  price: 0.09,   priceReverse: 0.26,  value: 3.10   },
  { number: 49,  name: "Haunter",               rarity: "C",    regular: 17, reverse: 6,  price: 0.19,   priceReverse: 0.28,  value: 4.91   },
  { number: 50,  name: "Gengar",                rarity: "R",    regular: 11, reverse: 3,  price: 0.56,   priceReverse: 1.62,  value: 11.02  },
  { number: 51,  name: "Skorupi",               rarity: "C",    regular: 18, reverse: 7,  price: 0.09,   priceReverse: 0.19,  value: 2.95   },
  { number: 52,  name: "Drapion",               rarity: "U",    regular: 36, reverse: 4,  price: 0.07,   priceReverse: 0.19,  value: 3.28   },
  { number: 53,  name: "Yveltal ex",            rarity: "RR",   regular: 8,  reverse: 0,  price: 0.43,                        value: 3.44   },
  { number: 54,  name: "Chien-Pao",             rarity: "R",    regular: 13, reverse: 6,  price: 0.18,   priceReverse: 0.14,  value: 3.18   },
  { number: 55,  name: "Mega Skarmory ex",      rarity: "RR",   regular: 4,  reverse: 0,  price: 0.41,                        value: 1.64   },
  { number: 56,  name: "Honedge",               rarity: "C",    regular: 24, reverse: 5,  price: 0.13,   priceReverse: 0.31,  value: 4.67   },
  { number: 57,  name: "Doublade",              rarity: "C",    regular: 21, reverse: 6,  price: 0.07,   priceReverse: 0.24,  value: 2.91   },
  { number: 58,  name: "Aegislash",             rarity: "U",    regular: 23, reverse: 6,  price: 0.09,   priceReverse: 0.26,  value: 3.63   },
  { number: 59,  name: "Klefki",                rarity: "C",    regular: 20, reverse: 7,  price: 0.09,   priceReverse: 0.22,  value: 3.34   },
  { number: 60,  name: "Rattata",               rarity: "C",    regular: 23, reverse: 4,  price: 0.10,   priceReverse: 0.23,  value: 3.22   },
  { number: 61,  name: "Raticate",              rarity: "U",    regular: 23, reverse: 7,  price: 0.05,   priceReverse: 0.26,  value: 2.97   },
  { number: 62,  name: "Meowth ex",             rarity: "RR",   regular: 5,  reverse: 0,  price: 2.86,                        value: 14.30  },
  { number: 63,  name: "Snorlax",               rarity: "C",    regular: 17, reverse: 7,  price: 0.11,   priceReverse: 0.28,  value: 3.83   },
  { number: 64,  name: "Bunnelby",              rarity: "C",    regular: 20, reverse: 3,  price: 0.04,   priceReverse: 0.24,  value: 1.52   },
  { number: 65,  name: "Diggerby",              rarity: "U",    regular: 23, reverse: 6,  price: 0.04,   priceReverse: 0.24,  value: 2.36   },
  { number: 66,  name: "Fletchling",            rarity: "C",    regular: 20, reverse: 7,  price: 0.13,   priceReverse: 0.21,  value: 4.07   },
  { number: 67,  name: "Furfrou",               rarity: "C",    regular: 20, reverse: 7,  price: 0.05,   priceReverse: 0.19,  value: 2.33   },
  { number: 68,  name: "Jaw Fossil",            rarity: "C",    regular: 15, reverse: 3,  price: 0.16,   priceReverse: 0.21,  value: 3.03   },
  { number: 69,  name: "Sail Fossil",           rarity: "C",    regular: 15, reverse: 5,  price: 0.13,   priceReverse: 0.26,  value: 3.25   },
  { number: 70,  name: "Core Memory",           rarity: "U",    regular: 23, reverse: 5,  price: 0.11,   priceReverse: 0.21,  value: 3.58   },
  { number: 71,  name: "Crushing Hammer",       rarity: "C",    regular: 15, reverse: 5,  price: 0.17,   priceReverse: 0.27,  value: 3.90   },
  { number: 72,  name: "Energy Search",         rarity: "C",    regular: 17, reverse: 6,  price: 0.15,   priceReverse: 0.25,  value: 4.05   },
  { number: 73,  name: "Energy Swatter",        rarity: "U",    regular: 29, reverse: 4,  price: 0.11,   priceReverse: 0.26,  value: 4.23   },
  { number: 74,  name: "Hole-Digging Shovel",   rarity: "C",    regular: 15, reverse: 3,  price: 0.17,   priceReverse: 0.21,  value: 3.18   },
  { number: 75,  name: "Jacinthe",              rarity: "U",    regular: 22, reverse: 3,  price: 0.14,   priceReverse: 0.26,  value: 3.86   },
  { number: 76,  name: "Judge",                 rarity: "U",    regular: 31, reverse: 2,  price: 0.24,   priceReverse: 0.24,  value: 7.92   },
  { number: 77,  name: "Lumiose City",          rarity: "U",    regular: 23, reverse: 3,  price: 0.11,   priceReverse: 0.18,  value: 3.07   },
  { number: 78,  name: "Lumiose Galette",       rarity: "U",    regular: 22, reverse: 8,  price: 0.06,   priceReverse: 0.20,  value: 2.92   },
  { number: 79,  name: "Naveen",                rarity: "U",    regular: 29, reverse: 3,  price: 0.11,   priceReverse: 0.21,  value: 3.82   },
  { number: 80,  name: "Poke Ball",             rarity: "C",    regular: 13, reverse: 6,  price: 0.08,   priceReverse: 0.22,  value: 2.36   },
  { number: 81,  name: "Poke Pad",              rarity: "U",    regular: 27, reverse: 4,  price: 0.30,   priceReverse: 0.57,  value: 10.38  },
  { number: 82,  name: "Pokemon Catcher",       rarity: "C",    regular: 14, reverse: 5,  price: 0.20,   priceReverse: 0.28,  value: 4.20   },
  { number: 83,  name: "Potion",                rarity: "C",    regular: 17, reverse: 5,  price: 0.12,   priceReverse: 0.24,  value: 3.24   },
  { number: 84,  name: "Rosa's Encouragement",  rarity: "U",    regular: 28, reverse: 5,  price: 0.14,   priceReverse: 0.27,  value: 5.27   },
  { number: 85,  name: "Tarragon",              rarity: "U",    regular: 24, reverse: 5,  price: 0.13,   priceReverse: 0.27,  value: 4.47   },
  { number: 86,  name: "Growing Energy",        rarity: "R",    regular: 14, reverse: 5,  price: 0.24,   priceReverse: 0.21,  value: 4.41   },
  { number: 87,  name: "Rocky Energy",          rarity: "R",    regular: 14, reverse: 5,  price: 0.24,   priceReverse: 0.25,  value: 4.61   },
  { number: 88,  name: "Telepathic Energy",     rarity: "R",    regular: 14, reverse: 6,  price: 0.33,   priceReverse: 0.29,  value: 6.36   },
  { number: 89,  name: "Spewpa",                rarity: "AR",   regular: 1,  reverse: 0,  price: 2.42,                        value: 2.42   },
  { number: 90,  name: "Rowlet",                rarity: "AR",   regular: 1,  reverse: 0,  price: 6.84,                        value: 6.84   },
  { number: 91,  name: "Talonflame",            rarity: "AR",   regular: 1,  reverse: 0,  price: 2.69,                        value: 2.69   },
  { number: 92,  name: "Aurorus",               rarity: "AR",   regular: 1,  reverse: 0,  price: 3.60,                        value: 3.60   },
  { number: 93,  name: "Dedenne",               rarity: "AR",   regular: 1,  reverse: 0,  price: 6.61,                        value: 6.61   },
  { number: 94,  name: "Clefairy",              rarity: "AR",   regular: 1,  reverse: 0,  price: 27.81,                       value: 27.81  },
  { number: 95,  name: "Espurr",                rarity: "AR",   regular: 1,  reverse: 0,  price: 6.00,                        value: 6.00   },
  { number: 96,  name: "Probopass",             rarity: "AR",   regular: 1,  reverse: 0,  price: 1.15,                        value: 1.15   },
  { number: 97,  name: "Drapion",               rarity: "AR",   regular: 1,  reverse: 0,  price: 1.50,                        value: 1.50   },
  { number: 98,  name: "Doublade",              rarity: "AR",   regular: 1,  reverse: 0,  price: 2.77,                        value: 2.77   },
  { number: 99,  name: "Raticate",              rarity: "AR",   regular: 1,  reverse: 0,  price: 3.22,                        value: 3.22   },
  { number: 100, name: "Decidueye ex",          rarity: "UR",   regular: 1,  reverse: 0,  price: 2.25,                        value: 2.25   },
  { number: 101, name: "Salazzle ex",           rarity: "UR",   regular: 1,  reverse: 0,  price: 1.88,                        value: 1.88   },
  { number: 102, name: "Mega Starmie ex",       rarity: "UR",   regular: 1,  reverse: 0,  price: 10.95,                       value: 10.95  },
  { number: 103, name: "Mega Clefable ex",      rarity: "UR",   regular: 1,  reverse: 0,  price: 7.99,                        value: 7.99   },
  { number: 104, name: "Mega Zygarde ex",       rarity: "UR",   regular: 1,  reverse: 0,  price: 8.75,                        value: 8.75   },
  { number: 105, name: "Yveltal ex",            rarity: "UR",   regular: 1,  reverse: 0,  price: 5.37,                        value: 5.37   },
  { number: 106, name: "Mega Skarmory ex",      rarity: "UR",   regular: 1,  reverse: 0,  price: 4.82,                        value: 4.82   },
  { number: 107, name: "Meowth ex",             rarity: "UR",   regular: 1,  reverse: 0,  price: 15.83,                       value: 15.83  },
  { number: 108, name: "Energy Recycler",       rarity: "UR",   regular: 1,  reverse: 0,  price: 3.11,                        value: 3.11   },
  { number: 109, name: "Forest of Vitality",    rarity: "UR",   regular: 1,  reverse: 0,  price: 7.12,                        value: 7.12   },
  { number: 110, name: "Jacinthe",              rarity: "UR",   regular: 1,  reverse: 0,  price: 3.42,                        value: 3.42   },
  { number: 111, name: "Lumiose City",          rarity: "UR",   regular: 1,  reverse: 0,  price: 2.46,                        value: 2.46   },
  { number: 112, name: "Naveen",                rarity: "UR",   regular: 1,  reverse: 0,  price: 2.46,                        value: 2.46   },
  { number: 113, name: "Poke Pad",              rarity: "UR",   regular: 1,  reverse: 0,  price: 14.83,                       value: 14.83  },
  { number: 114, name: "Rosa's Encouragement",  rarity: "UR",   regular: 1,  reverse: 0,  price: 5.97,                        value: 5.97   },
  { number: 115, name: "Sacred Ash",            rarity: "UR",   regular: 1,  reverse: 0,  price: 2.40,                        value: 2.40   },
  { number: 116, name: "Tarragon",              rarity: "UR",   regular: 1,  reverse: 0,  price: 3.05,                        value: 3.05   },
  { number: 117, name: "Wondrous Patch",        rarity: "UR",   regular: 1,  reverse: 0,  price: 3.45,                        value: 3.45   },
  { number: 118, name: "Mega Starmie ex",       rarity: "SIR",  regular: 1,  reverse: 0,  price: 63.23,                       value: 63.23  },
  { number: 119, name: "Mega Clefable ex",      rarity: "SIR",  regular: 1,  reverse: 0,  price: 70.54,                       value: 70.54  },
  { number: 120, name: "Mega Zygarde ex",       rarity: "SIR",  regular: 1,  reverse: 0,  price: 71.19,                       value: 71.19  },
  { number: 121, name: "Meowth ex",             rarity: "SIR",  regular: 1,  reverse: 0,  price: 181.91,                      value: 181.91 },
  { number: 122, name: "Jacinthe",              rarity: "SIR",  regular: 1,  reverse: 0,  price: 34.36,                       value: 34.36  },
  { number: 123, name: "Rosa's Encouragement",  rarity: "SIR",  regular: 1,  reverse: 0,  price: 68.89,                       value: 68.89  },
  { number: 124, name: "Mega Zygarde ex",       rarity: "Gold", regular: 1,  reverse: 0,  price: 171.10,                      value: 171.10 },
];
