export const IMAGE_BASE = "https://dz3we2x72f7ol.cloudfront.net/expansions/perfect-order/en-us";
export const IMAGE_CODE = "P614_EN";

export const HAS_REVERSE = new Set(["C", "U", "R"]);

export const RARITY_ORDER = ["C", "U", "R", "RR", "AR", "UR", "SIR", "Gold"];

export const RARITY_CONFIG = {
  C:    { label: "Common",                      color: "#94a3b8" },
  U:    { label: "Uncommon",                    color: "#34d399" },
  R:    { label: "Rare",                        color: "#60a5fa" },
  RR:   { label: "Double Rare",                 color: "#c084fc" },
  AR:   { label: "Art Rare",                    color: "#fb923c" },
  UR:   { label: "Special Rare",                color: "#f87171" },
  SIR:  { label: "Special Illustration Rare",   color: null },
  Gold: { label: "Gold",                        color: "#fbbf24" },
};

export const cards = [
  { number: 1,   name: "Spinarak",              rarity: "C",    regular: 6,  reverse: 4,  price: 0.14,   priceReverse: 0.18,  value: 1.56   },
  { number: 2,   name: "Aridos",                rarity: "C",    regular: 10, reverse: 3,  price: 0.08,   priceReverse: 0.17,  value: 1.31   },
  { number: 3,   name: "Shaymin",               rarity: "U",    regular: 6,  reverse: 1,  price: 0.11,   priceReverse: 0.21,  value: 0.87   },
  { number: 4,   name: "Snivy",                 rarity: "C",    regular: 6,  reverse: 1,  price: 0.10,   priceReverse: 0.23,  value: 0.83   },
  { number: 5,   name: "Servine",               rarity: "C",    regular: 5,  reverse: 2,  price: 0.12,   priceReverse: 0.21,  value: 1.02   },
  { number: 6,   name: "Serperior",             rarity: "R",    regular: 6,  reverse: 1,  price: 0.12,   priceReverse: 0.19,  value: 0.91   },
  { number: 7,   name: "Scatterbug",            rarity: "C",    regular: 9,  reverse: 2,  price: 0.14,   priceReverse: 0.20,  value: 1.66   },
  { number: 8,   name: "Spewpa",                rarity: "C",    regular: 6,  reverse: 1,  price: 0.12,   priceReverse: 0.23,  value: 0.95   },
  { number: 9,   name: "Vivillion",             rarity: "U",    regular: 14, reverse: 0,  price: 0.14,   priceReverse: 0.29,  value: 1.96   },
  { number: 10,  name: "Rowlet",                rarity: "C",    regular: 11, reverse: 1,  price: 0.12,   priceReverse: 0.22,  value: 1.54   },
  { number: 11,  name: "Dartrix",               rarity: "C",    regular: 3,  reverse: 2,  price: 0.14,   priceReverse: 0.27,  value: 0.96   },
  { number: 12,  name: "Decidueye ex",          rarity: "RR",   regular: 2,  reverse: 0,  price: 0.50,                        value: 1.00   },
  { number: 13,  name: "Fletchinder",           rarity: "C",    regular: 9,  reverse: 2,  price: 0.09,   priceReverse: 0.17,  value: 1.15   },
  { number: 14,  name: "Talonflame",            rarity: "U",    regular: 11, reverse: 1,  price: 0.14,   priceReverse: 0.17,  value: 1.71   },
  { number: 15,  name: "Salandit",              rarity: "C",    regular: 7,  reverse: 3,  price: 0.13,   priceReverse: 0.17,  value: 1.42   },
  { number: 16,  name: "Salazzle ex",           rarity: "RR",   regular: 2,  reverse: 0,  price: 0.46,                        value: 0.92   },
  { number: 17,  name: "Turtonator",            rarity: "U",    regular: 8,  reverse: 2,  price: 0.11,   priceReverse: 0.19,  value: 1.26   },
  { number: 18,  name: "Seel",                  rarity: "C",    regular: 6,  reverse: 4,  price: 0.07,   priceReverse: 0.14,  value: 0.98   },
  { number: 19,  name: "Dewgong",               rarity: "R",    regular: 7,  reverse: 2,  price: 0.15,   priceReverse: 0.26,  value: 1.57   },
  { number: 20,  name: "Staryu",                rarity: "C",    regular: 11, reverse: 0,  price: 0.15,   priceReverse: 0.20,  value: 1.65   },
  { number: 21,  name: "Mega Starmie ex",       rarity: "RR",   regular: 4,  reverse: 0,  price: 0.87,                        value: 3.48   },
  { number: 22,  name: "Lapras ex",             rarity: "RR",   regular: 1,  reverse: 0,  price: 0.53,                        value: 0.53   },
  { number: 23,  name: "Amaura",                rarity: "C",    regular: 8,  reverse: 1,  price: 0.17,   priceReverse: 0.21,  value: 1.57   },
  { number: 24,  name: "Aurorus",               rarity: "R",    regular: 4,  reverse: 1,  price: 0.18,   priceReverse: 0.28,  value: 1.00   },
  { number: 25,  name: "Volcanion",             rarity: "U",    regular: 8,  reverse: 1,  price: 0.09,   priceReverse: 0.21,  value: 0.93   },
  { number: 26,  name: "Shinx",                 rarity: "C",    regular: 4,  reverse: 2,  price: 0.13,   priceReverse: 0.15,  value: 0.82   },
  { number: 27,  name: "Luxio",                 rarity: "U",    regular: 10, reverse: 2,  price: 0.12,   priceReverse: 0.20,  value: 1.60   },
  { number: 28,  name: "Luxray",                rarity: "R",    regular: 4,  reverse: 2,  price: 0.12,   priceReverse: 0.25,  value: 0.98   },
  { number: 29,  name: "Dedenne",               rarity: "C",    regular: 9,  reverse: 1,  price: 0.14,   priceReverse: 0.23,  value: 1.49   },
  { number: 30,  name: "Clefairy",              rarity: "C",    regular: 6,  reverse: 1,  price: 0.12,   priceReverse: 0.22,  value: 0.94   },
  { number: 31,  name: "Mega Clefable ex",      rarity: "RR",   regular: 1,  reverse: 0,  price: 0.57,                        value: 0.57   },
  { number: 32,  name: "Mawile",                rarity: "C",    regular: 2,  reverse: 2,  price: 0.15,   priceReverse: 0.20,  value: 0.70   },
  { number: 33,  name: "Espurr",                rarity: "C",    regular: 6,  reverse: 1,  price: 0.15,   priceReverse: 0.17,  value: 1.07   },
  { number: 34,  name: "Meowstic",              rarity: "U",    regular: 8,  reverse: 3,  price: 0.12,   priceReverse: 0.24,  value: 1.68   },
  { number: 35,  name: "Spritzee",              rarity: "C",    regular: 6,  reverse: 0,  price: 0.07,   priceReverse: 0.17,  value: 0.42   },
  { number: 36,  name: "Aromatisse",            rarity: "U",    regular: 6,  reverse: 1,  price: 0.11,   priceReverse: 0.20,  value: 0.86   },
  { number: 37,  name: "Nosepass",              rarity: "C",    regular: 5,  reverse: 0,  price: 0.11,   priceReverse: 0.16,  value: 0.55   },
  { number: 38,  name: "Probopass",             rarity: "C",    regular: 9,  reverse: 3,  price: 0.10,   priceReverse: 0.20,  value: 1.50   },
  { number: 39,  name: "Hippopoatas",           rarity: "C",    regular: 9,  reverse: 2,  price: 0.10,   priceReverse: 0.15,  value: 1.20   },
  { number: 40,  name: "Hippowdon",             rarity: "U",    regular: 8,  reverse: 1,  price: 0.12,   priceReverse: 0.22,  value: 1.18   },
  { number: 41,  name: "Landorus",              rarity: "R",    regular: 4,  reverse: 1,  price: 0.08,   priceReverse: 0.18,  value: 0.50   },
  { number: 42,  name: "Binacle",               rarity: "C",    regular: 10, reverse: 2,  price: 0.16,   priceReverse: 0.26,  value: 2.12   },
  { number: 43,  name: "Barbarcle",             rarity: "U",    regular: 6,  reverse: 2,  price: 0.13,   priceReverse: 0.32,  value: 1.42   },
  { number: 44,  name: "Tyrunt",                rarity: "C",    regular: 9,  reverse: 3,  price: 0.18,   priceReverse: 0.27,  value: 2.43   },
  { number: 45,  name: "Tyrantrum",             rarity: "R",    regular: 7,  reverse: 3,  price: 0.18,   priceReverse: 0.28,  value: 2.10   },
  { number: 46,  name: "Hawlucha",              rarity: "C",    regular: 5,  reverse: 2,  price: 0.09,   priceReverse: 0.25,  value: 0.95   },
  { number: 47,  name: "Mega Zygarde ex",       rarity: "RR",   regular: 2,  reverse: 0,  price: 0.70,                        value: 1.40   },
  { number: 48,  name: "Gastly",                rarity: "C",    regular: 5,  reverse: 1,  price: 0.15,   priceReverse: 0.22,  value: 0.97   },
  { number: 49,  name: "Haunter",               rarity: "C",    regular: 5,  reverse: 2,  price: 0.19,   priceReverse: 0.24,  value: 1.43   },
  { number: 50,  name: "Gengar",                rarity: "R",    regular: 3,  reverse: 0,  price: 0.53,   priceReverse: 0.66,  value: 1.59   },
  { number: 51,  name: "Skorupi",               rarity: "C",    regular: 3,  reverse: 4,  price: 0.12,   priceReverse: 0.20,  value: 1.16   },
  { number: 52,  name: "Drapion",               rarity: "U",    regular: 12, reverse: 1,  price: 0.07,   priceReverse: 0.19,  value: 1.03   },
  { number: 53,  name: "Yveltal ex",            rarity: "RR",   regular: 3,  reverse: 0,  price: 0.45,                        value: 1.35   },
  { number: 54,  name: "Chien-Pao",             rarity: "R",    regular: 2,  reverse: 0,  price: 0.13,   priceReverse: 0.20,  value: 0.26   },
  { number: 55,  name: "Mega Skarmory ex",      rarity: "RR",   regular: 1,  reverse: 0,  price: 0.52,                        value: 0.52   },
  { number: 56,  name: "Honedge",               rarity: "C",    regular: 5,  reverse: 2,  price: 0.17,   priceReverse: 0.24,  value: 1.33   },
  { number: 57,  name: "Doublade",              rarity: "C",    regular: 6,  reverse: 1,  price: 0.12,   priceReverse: 0.21,  value: 0.93   },
  { number: 58,  name: "Aegislash",             rarity: "U",    regular: 11, reverse: 1,  price: 0.12,   priceReverse: 0.20,  value: 1.52   },
  { number: 59,  name: "Klefki",                rarity: "C",    regular: 10, reverse: 4,  price: 0.11,   priceReverse: 0.23,  value: 2.02   },
  { number: 60,  name: "Rattata",               rarity: "C",    regular: 6,  reverse: 0,  price: 0.11,   priceReverse: 0.21,  value: 0.66   },
  { number: 61,  name: "Raticate",              rarity: "U",    regular: 7,  reverse: 4,  price: 0.10,   priceReverse: 0.23,  value: 1.62   },
  { number: 62,  name: "Meowth ex",             rarity: "RR",   regular: 2,  reverse: 0,  price: 5.10,                        value: 10.20  },
  { number: 63,  name: "Snorlax",               rarity: "C",    regular: 7,  reverse: 2,  price: 0.19,   priceReverse: 0.29,  value: 1.91   },
  { number: 64,  name: "Bunnelby",              rarity: "C",    regular: 4,  reverse: 0,  price: 0.07,   priceReverse: 0.16,  value: 0.28   },
  { number: 65,  name: "Diggerby",              rarity: "U",    regular: 8,  reverse: 1,  price: 0.14,   priceReverse: 0.22,  value: 1.34   },
  { number: 66,  name: "Fletchling",            rarity: "C",    regular: 11, reverse: 1,  price: 0.10,   priceReverse: 0.19,  value: 1.29   },
  { number: 67,  name: "Furfrou",               rarity: "C",    regular: 7,  reverse: 3,  price: 0.08,   priceReverse: 0.18,  value: 1.10   },
  { number: 68,  name: "Jaw Fossil",            rarity: "C",    regular: 6,  reverse: 1,  price: 0.15,   priceReverse: 0.21,  value: 1.11   },
  { number: 69,  name: "Sail Fossil",           rarity: "C",    regular: 5,  reverse: 2,  price: 0.11,   priceReverse: 0.20,  value: 0.95   },
  { number: 70,  name: "Core Memory",           rarity: "U",    regular: 9,  reverse: 3,  price: 0.14,   priceReverse: 0.19,  value: 1.83   },
  { number: 71,  name: "Crushing Hammer",       rarity: "C",    regular: 4,  reverse: 2,  price: 0.10,   priceReverse: 0.17,  value: 0.74   },
  { number: 72,  name: "Energy Search",         rarity: "C",    regular: 7,  reverse: 2,  price: 0.11,   priceReverse: 0.20,  value: 1.17   },
  { number: 73,  name: "Energy Swatter",        rarity: "U",    regular: 11, reverse: 2,  price: 0.10,   priceReverse: 0.26,  value: 1.62   },
  { number: 74,  name: "Hole-Digging Shovel",   rarity: "C",    regular: 6,  reverse: 2,  price: 0.17,   priceReverse: 0.15,  value: 1.32   },
  { number: 75,  name: "Jacinthe",              rarity: "U",    regular: 6,  reverse: 1,  price: 0.12,   priceReverse: 0.20,  value: 0.92   },
  { number: 76,  name: "Judge",                 rarity: "U",    regular: 12, reverse: 0,  price: 0.14,   priceReverse: 0.20,  value: 1.68   },
  { number: 77,  name: "Lumiose City",          rarity: "U",    regular: 7,  reverse: 1,  price: 0.04,   priceReverse: 0.22,  value: 0.50   },
  { number: 78,  name: "Lumiose Galette",       rarity: "U",    regular: 4,  reverse: 5,  price: 0.22,   priceReverse: 0.17,  value: 1.73   },
  { number: 79,  name: "Naveen",                rarity: "U",    regular: 10, reverse: 0,  price: 0.12,   priceReverse: 0.20,  value: 1.20   },
  { number: 80,  name: "Poke Ball",             rarity: "C",    regular: 5,  reverse: 2,  price: 0.10,   priceReverse: 0.19,  value: 0.88   },
  { number: 81,  name: "Poke Pad",              rarity: "U",    regular: 9,  reverse: 2,  price: 0.47,   priceReverse: 0.86,  value: 5.95   },
  { number: 82,  name: "Pokemon Catcher",       rarity: "C",    regular: 3,  reverse: 2,  price: 0.12,   priceReverse: 0.14,  value: 0.64   },
  { number: 83,  name: "Potion",                rarity: "C",    regular: 7,  reverse: 1,  price: 0.17,   priceReverse: 0.22,  value: 1.41   },
  { number: 84,  name: "Rosa's Encouragement",  rarity: "U",    regular: 12, reverse: 1,  price: 0.16,   priceReverse: 0.26,  value: 2.18   },
  { number: 85,  name: "Tarragon",              rarity: "U",    regular: 12, reverse: 2,  price: 0.16,   priceReverse: 0.29,  value: 2.50   },
  { number: 86,  name: "Growing Energy",        rarity: "R",    regular: 1,  reverse: 0,  price: 0.17,   priceReverse: 0.25,  value: 0.17   },
  { number: 87,  name: "Rocky Energy",          rarity: "R",    regular: 7,  reverse: 2,  price: 0.24,   priceReverse: 0.31,  value: 2.30   },
  { number: 88,  name: "Telepathic Energy",     rarity: "R",    regular: 5,  reverse: 4,  price: 0.29,   priceReverse: 0.43,  value: 3.17   },
  { number: 89,  name: "Spewpa",                rarity: "AR",   regular: 1,  reverse: 0,  price: 2.56,                        value: 2.56   },
  { number: 90,  name: "Rowlet",                rarity: "AR",   regular: 0,  reverse: 0,  price: 5.69,                        value: 0.00   },
  { number: 91,  name: "Talonflame",            rarity: "AR",   regular: 1,  reverse: 0,  price: 2.97,                        value: 2.97   },
  { number: 92,  name: "Aurorus",               rarity: "AR",   regular: 1,  reverse: 0,  price: 4.11,                        value: 4.11   },
  { number: 93,  name: "Dedenne",               rarity: "AR",   regular: 2,  reverse: 0,  price: 7.00,                        value: 14.00  },
  { number: 94,  name: "Clefairy",              rarity: "AR",   regular: 2,  reverse: 0,  price: 29.39,                       value: 58.78  },
  { number: 95,  name: "Espurr",                rarity: "AR",   regular: 1,  reverse: 0,  price: 4.87,                        value: 4.87   },
  { number: 96,  name: "Probopass",             rarity: "AR",   regular: 0,  reverse: 0,  price: 1.48,                        value: 0.00   },
  { number: 97,  name: "Drapion",               rarity: "AR",   regular: 0,  reverse: 0,  price: 1.70,                        value: 0.00   },
  { number: 98,  name: "Doublade",              rarity: "AR",   regular: 0,  reverse: 0,  price: 3.88,                        value: 0.00   },
  { number: 99,  name: "Raticate",              rarity: "AR",   regular: 0,  reverse: 0,  price: 3.69,                        value: 0.00   },
  { number: 100, name: "Decidueye ex",          rarity: "UR",   regular: 0,  reverse: 0,  price: 4.43,                        value: 0.00   },
  { number: 101, name: "Salazzle ex",           rarity: "UR",   regular: 1,  reverse: 0,  price: 2.66,                        value: 2.66   },
  { number: 102, name: "Mega Starmie ex",       rarity: "UR",   regular: 0,  reverse: 0,  price: 13.60,                       value: 0.00   },
  { number: 103, name: "Mega Clefable ex",      rarity: "UR",   regular: 0,  reverse: 0,  price: 7.68,                        value: 0.00   },
  { number: 104, name: "Mega Zygarde ex",       rarity: "UR",   regular: 0,  reverse: 0,  price: 11.70,                       value: 0.00   },
  { number: 105, name: "Yveltal ex",            rarity: "UR",   regular: 0,  reverse: 0,  price: 7.23,                        value: 0.00   },
  { number: 106, name: "Mega Skarmory ex",      rarity: "UR",   regular: 0,  reverse: 0,  price: 6.46,                        value: 0.00   },
  { number: 107, name: "Meowth ex",             rarity: "UR",   regular: 1,  reverse: 0,  price: 21.06,                       value: 21.06  },
  { number: 108, name: "Energy Recycler",       rarity: "UR",   regular: 0,  reverse: 0,  price: 3.84,                        value: 0.00   },
  { number: 109, name: "Forest of Vitality",    rarity: "UR",   regular: 0,  reverse: 0,  price: 7.54,                        value: 0.00   },
  { number: 110, name: "Jacinthe",              rarity: "UR",   regular: 0,  reverse: 0,  price: 5.13,                        value: 0.00   },
  { number: 111, name: "Lumiose City",          rarity: "UR",   regular: 0,  reverse: 0,  price: 3.05,                        value: 0.00   },
  { number: 112, name: "Naveen",                rarity: "UR",   regular: 0,  reverse: 0,  price: 3.13,                        value: 0.00   },
  { number: 113, name: "Poke Pad",              rarity: "UR",   regular: 0,  reverse: 0,  price: 17.84,                       value: 0.00   },
  { number: 114, name: "Rosa's Encouragement",  rarity: "UR",   regular: 0,  reverse: 0,  price: 10.57,                       value: 0.00   },
  { number: 115, name: "Sacred Ash",            rarity: "UR",   regular: 0,  reverse: 0,  price: 2.98,                        value: 0.00   },
  { number: 116, name: "Tarragon",              rarity: "UR",   regular: 0,  reverse: 0,  price: 4.29,                        value: 0.00   },
  { number: 117, name: "Wondrous Patch",        rarity: "UR",   regular: 0,  reverse: 0,  price: 5.11,                        value: 0.00   },
  { number: 118, name: "Mega Starmie ex",       rarity: "SIR",  regular: 0,  reverse: 0,  price: 75.55,                       value: 0.00   },
  { number: 119, name: "Mega Clefable ex",      rarity: "SIR",  regular: 0,  reverse: 0,  price: 73.58,                       value: 0.00   },
  { number: 120, name: "Mega Zygarde ex",       rarity: "SIR",  regular: 0,  reverse: 0,  price: 91.89,                       value: 0.00   },
  { number: 121, name: "Meowth ex",             rarity: "SIR",  regular: 0,  reverse: 0,  price: 168.69,                      value: 0.00   },
  { number: 122, name: "Jacinthe",              rarity: "SIR",  regular: 1,  reverse: 0,  price: 34.05,                       value: 34.05  },
  { number: 123, name: "Rosa's Encouragement",  rarity: "SIR",  regular: 0,  reverse: 0,  price: 74.75,                       value: 0.00   },
  { number: 124, name: "Mega Zygarde ex",       rarity: "Gold", regular: 0,  reverse: 0,  price: 160.23,                      value: 0.00   },
];
